spring:
  application:
    name: demo


  datasource:
    url: jdbc:mysql://${my-data.db-host}:${my-data.db-port}/${my-data.db-name}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    driver-class-name: ${my-data.db-driver}
    username: ${my-data.db-username}
    password: ${my-data.db-password}


my-data:
  db-driver: com.mysql.cj.jdbc.Driver
  db-host: 172.16.10.117
  db-port: 3306
  db-name: test
  db-username: root
  db-password: 123

test:
  data1: 111
  data2: 222

mybatis-plus:
  global-config:
    db-config:
      id-type: auto # id自增长
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #sql语句在控制台输出

